insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(2, "Películas para no dormir: Regreso a Moira (Films to Keep You Awake: Spectre)", "An elderly writer visits the small coastal village where he was born and raised. He reminisces of his childhood, and the beautiful, mysterious woman he's been unable to forget. As he walks through his old village he catches ghostly glimpses of the same woman, and recalls the dark story of their forbidden love affair.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(3, "The Spectre of Edgar Allan Poe", "With only the slightest basis in fact, this horror film purports to chronicle an incident from the life of Edgar Allen Poe. It has to do with his mad 13-year-old cousin Lenore, whom Poe deeply loved. She is insane and lives in an asylum. Poe visits there and discovers that the hospital is but a facade for a terrifying chamber of horrors.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(4, "DC Showcase: The Spectre", "As Detective Jim Corrigan investigates a murder, The Spectre delivers horrific justice to the perpetrators.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(6, "Spectre", "A cryptic message from Bond's past sends him on a trail to uncover a sinister organisation. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind Spectre.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(7, "The Spectre Of Hope", "Over the past 30 years Brazilian photographer Sebastião Salgado's work has won every major award for excellence. More importantly, his photographs have had an actual impact on the world and how it is seen, bringing conditions of famine and poverty to the attention of a jaded first world in a profound and arresting way. In THE SPECTRE OF HOPE Sebastião Salgado joins Berger to pore over Salgado's collection "Migrations." Six years and 43 countries in the making (ranging across Africa, Asia, Eastern Europe and Latin America), "Migrations" contains photographs of people pushed from their homes and traditions to cities and their margins - slums and streets and refugee camps.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(8, "Claude Lanzmann: Spectres of the Shoah", "Director Claude Lanzmann discusses the filming of his groundbreaking 1985 documentary Shoah.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(9, "Spectres are haunting Europe", "The daily life of refugees (Syrian, Kurdish, Pakistani, Afghani, and other) in the camp of Idomeni. Refugees waiting in queues for food, tea and doctors; waiting to cross the border between Greece and Macedonia. One day, Europe closes its borders for them once and for all. The "residents" of Idomeni decide, in their turn, to occupy the train tracks, blocking the trains that carry goods across the border.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(11, "Spotlight Scandals", "In this musical comedy, a vaudevillian teams up with a barber and becomes a smash hit. The barber also finds himself falling in love with his talented partner. When he learns that she has a shot at becoming a famous radio singer, he decides to go solo.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(12, "Spotlight on a Murderer (Pleins feux sur l'assassin)", "Pleins Feux sur l'Assassin is a passable murder mystery by Georges Franju set in the atmospheric interior of an old chateau and involving the heirs to a fortune. The dying man whose fortune it is has played an unusual trick on those who would have his riches. He has hidden himself in a secret room inside the chateau, knowing that his body has to be found before the castle can be passed on as an inheritance. The would-be heirs are caught in a dilemma but decide to turn the venerable structure into a light-and-sound show extravaganza in order to attract tourist money. That is just fine, except a series of accidents among them soon begins to look like murder. ~ Eleanor Mannikka, Rovi", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(14, "American Girl: Isabelle Dances into the Spotlight", "Nine-year-old Isabelle is an inspired dancer with a flair for fashion design. She's thrilled to be studying ballet at a prestigious performing arts school, but her classmates are so talented and she can't help feeling that she's always in the shadow of her "perfect" older sister, Jade. So when her idol, a famous ballerina, encourages her to audition for a professional ballet, Isabelle isn't sure she can land the role. And when a competitive classmate starts pointing out Isabelle's every mistake, her confidence sinks even further. Can she find the courage to step into the spotlight and discover her own way to shine?", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(15, "Spotlight", "SPOTLIGHT tells the riveting true story of the Pulitzer Prize-winning Boston Globe investigation that would rock the city and cause a crisis in one of the world's oldest and most trusted institutions. When the newspaper's tenacious "Spotlight" team of reporters delves into allegations of abuse in the Catholic Church, their year-long investigation uncovers a decades-long cover-up at the highest levels of Boston's religious, legal, and government establishment, touching off a wave of revelations around the world. Directed by Academy Award-nominee Tom McCarthy, SPOTLIGHT is a tense investigative dramatic-thriller, tracing the steps to one of the biggest cover-ups in modern times. (C) Open Road", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(16, "Juneteenth Jamboree: Spotlight on Unsung Heroes", "African-American heroes from Texas history are recalled. Included: Mary E. Branch, who brought Tillotson College out of the Great Depression and into a flourishing future; and Jacob Fontaine, who was important in the founding of the University of Texas. Also: the story behind the Yellow Rose of Texas.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(18, "Star Wars: Episode VII - The Force Awakens", "The Star Wars saga continues with this seventh entry -- the first under the Walt Disney Co. umbrella. The film will act as the start of a new trilogy set after the events of Return of the Jedi. J.J. Abrams directs from a script by Michael Arndt. ~ Jeremy Wheeler, Rovi", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(19, "Steve Jobs: The Lost Interview", "In 1995, during the making of his TV series Triumph of the Nerds about the birth of the PC, Bob Cringely did a memorable hour-long interview with Steve Jobs. It was 10 years since Jobs had left Apple following a bruising struggle with John Sculley, the CEO he had brought into the company. At the time of the interview Jobs was running NeXT, the niche computer company he had founded after leaving Apple. During the interview, Jobs was at his charismatic best - witty, outspoken, visionary. In the end, only a part of the interview was used in the series and the rest was thought lost. But recently a VHS copy was found in the series director's garage. Now, cleaned up with modern technology, and put into context by Cringely, the entire interview will be screened in Landmark Theatres. -- (C) Official Site", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(20, "Steve Jobs: Visionary Genius (Steve Jobs: iGenius)", "This documentary examines the life of Steve Jobs, the co-founder of Apple and one of the most influential figures of the 21st century. His inventions have shaped how millions of people communicate, and the filmmakers showcase the reach and breadth of the man's accomplishments. ~ Perry Seibert, Rovi", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(21, "Steve Jobs: Consciously Genius", "Take a deeper look into Steve Job's life, and the ways he left a legacy.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(22, "Steve Jobs", "Set backstage at three iconic product launches and ending in 1998 with the unveiling of the iMac, Steve Jobs takes us behind the scenes of the digital revolution to paint an intimate portrait of the brilliant man at its epicenter.-- (C) Universal", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(23, "Steve Jobs: Man in the Machine", "A look at the personal and private life of the late Apple CEO, Steve Jobs.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(24, "Straight Outta Compton", "In the mid-1980s, the streets of Compton, California, were some of the most dangerous in the country. When five young men translated their experiences growing up into brutally honest music that rebelled against abusive authority, they gave an explosive voice to a silenced generation. Following the meteoric rise and fall of N.W.A., Straight Outta Compton tells the astonishing story of how these youngsters revolutionized music and pop culture forever the moment they told the world the truth about life in the hood and ignited a cultural war. -- (C) Universal Pictures", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(25, "The Tangerine Bear", "Jenna Elfman, Trisha Yearwood, Jonathan Taylor Thomas, and other luminaries contribute vocals to this animated children's holiday special featuring the inimitable Tangerine Bear.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(26, "Louise Bourgeois: The Spider, the Mistress and the Tangerine", "Born in 1911, sculptor Louise Bourgeois has been a major figure in contemporary American art since the early '60s, having earned an international reputation for her abstract pieces that embrace the appetites of human sexuality and the emotional dynamics of youth in a rich variety of ways. Filmmakers Marion Cajori and Amei Wallach offer an intriguing look at Bourgeois, her art, and her working methods in the documentary Louise Bourgeois: The Spider, the Mistress and the Tangerine. Active and alert in her mid-nineties, Bourgeois discusses how her life history impacts her work, her relationship with her family, the techniques she uses to create her sculptures, and how the emotional outlet of her art has helped her survive. The New York premiere of Louise Bourgeois: The Spider, the Mistress and the Tangerine was scheduled to coincide with the opening of a major retrospective of Bourgeois' work at the city's Guggenheim Museum; it was the last film from co-director Marion Cajori, who died in the summer of 2006 before it was completed.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(28, "The Candy Tangerine Man", "In this drama, a fine upstanding LA businessman, and caring family man, reveals a much darker side when the sun goes down and the lights go out. Eventually his secret is discovered: the fellow is a prominent Sunset Strip pimp.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(29, "Tangerine Dream: Three Phase", "The instrumental group performs in a 1992 Seattle concert that also features footage of band members at different stages of their careers. Included: "Two Bunch Palms," "Phaedra," "Oriental Haze," "Graffiti Street," "Backstreet Hero."", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(31, "Tangerines", "Set in 1992, during the growing conflict between Georgia and Abkhazian separatists in the wake of the Soviet Union's dissolution, this compassionate tale focuses on two Estonian immigrant farmers who decide to remain in Georgia long enough to harvest their tangerine crop. When the war comes to their doorsteps, Ivo (played by legendary Estonian actor Lembit Ulfsak) takes in two wounded soldiers from opposite sides. The fighters vow to kill each other when they recover, but their extended period of recovery has a humanizing effect that might transcend ethnic divides. Set against a beautiful landscape defiled by war, this poetic film makes an eloquent statement for peace. (C) Samuel Goldwyn", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(32, "Tangerine", "A working girl tears through Tinseltown on Christmas Eve searching for the pimp who broke her heart. (C) Magnolia", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(33, "Trumbo", "A documentary adaptation of the popular regional theatrical monologue -- in which such heavyweights as Paul Newman, Nathan Lane, and Joe Mantegna essayed the lead on various occasions -- Trumbo recounts the life and times of legendary Hollywood scribe-turned-HUAC scapegoat Dalton Trumbo. As with its source production, the film takes as its base material highly personal, detailed, and emotive letters written by Dalton Trumbo to his son, Christopher; the latter, in turn, molded the missives into a screenplay for this production. Here, however, in lieu of one actor portraying Dalton, a number of celebrities take turns narrating from the script, including Lane, Paul Giamatti, Brian Dennehy, Donald Sutherland, and others. As a visual accompaniment, the film intercuts home-movie footage from the Trumbos' lives; incisive interview material with Trumbo, his family, friends, and collaborators; and haunting glimpses of the HUAC trial hearings with the Hollywood Ten, led by Senator Joseph McCarthy; as well as extracts from The Sandpiper, Johnny Got His Gun, Spartacus, and other productions authored by Trumbo. Peter Askin, who helmed the stage play, directs. ~ Nathan Southern, Rovi", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(34, "Trumbo", "In 1947, Dalton Trumbo (Bryan Cranston) was Hollywood's top screenwriter until he and other artists were jailed and blacklisted for their political beliefs. TRUMBO (directed by Jay Roach) recounts how Dalton used words and wit to win two Academy Awards and expose the absurdity and injustice of the blacklist, which entangled everyone from gossip columnist Hedda Hopper (Helen Mirren) to John Wayne, Kirk Douglas and Otto Preminger.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(35, "American Honey", "Star, an adolescent girl from a troubled home, runs away with a traveling sales crew who drive across the American Midwest selling subscriptions door to door. Finding her feet in this gang of teenagers, one of whom is Jake, she soon gets into the group's lifestyle of hard-partying nights, law-bending days, and young love.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(36, "The Arrival", "A shy radio telescope operator named Zane Ziminski (Charlie Sheen) picks up a series of regular signals coming from space -- and deliberately pointed toward Earth. Convinced that he has discovered alien transmissions, Ziminski is first chastised and then fired by his boss (Ron Silver). Obsessed, he builds a makeshift radio telescope in his house to find out where the signals were sent. Convinced that they're intended for aliens already hidden on Earth, he tracks them to a bleak, isolated Mexican village, where he joins forces with a female scientist (Lindsay Crouse), who has suspicions of her own after witnessing an acceleration of global warming. The villagers turn out to be aliens, and the village a front for an underground alien complex. The aliens are here to "terraform" Earth and prepare it for the arrival of the rest of their race, who will die unless they leave their homeworld and colonize elsewhere. Only Ziminski can stop them. Written and directed by David N. Twohy, The Arrival is a throwback to the genre chillers of the '50s. ~ Don Kaye, Rovi", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(37, "The Second Arrival", "In this sci-fi adventure, a brave hero saves the Blue Planet from alien invaders and in so doing keeps a promise to his dead brother.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(38, "Ilona Arrives with the Rain", "Based on a novel by Colombian author Alvaro Mutis, this frothy adventure chronicles the exploits of an unlikely trio of wanderers trying to earn money in Panama City during the 1950s. As the film opens, the three have been separated. The dashing Marqroll is aboard a ship that gets confiscated in port. While marooned, he wanders the city and runs into his good friend, the vivacious Macedonian-Polish traveler Illona who lives a splendid life after having sold a lucrative South African nightclub. Upon learning that their Lebanese compatriot Abdul has been imprisoned for smuggling, the two conspire to spring him. Afterward, they decide to help Abdul buy the tramp steamer he has always wanted. To do this, they open up a brothel. It's a big success and their goal is in sight until they hire on the mysterious Larissa as their newest shady lady. ~ Sandra Brennan, Rovi", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(41, "Guiana 1838: The Arrival", "Set just four short years after slavery in the British Caribbean was officially abolished, Director Rohit Jagessar earnest period drama finds plantation overseer James Bullock desperately plotting new ways to get slaves back in the sugar cane fields. In order to fill the great void that was opened up by abolition, the Gillanders, Arbuthnot & Company in Calcutta (part of the East India Company) recruits ambitious small-timer Sinha to draw in unsuspecting Indians by exploiting their dreams of the elusive El Dorado. Signed to five year contracts as indentured servants, the so-called "Coolies" board a British slave ship and endure a grueling 112 day trip to British Guiana. Upon arriving at their destination, the helpless "Coolies" are brutally enslaved on the colony. One year later, British and Foreign Anti-Slavery Society representative John Scoble arrives at British Guiana to discover an insidious new brand of slavery that was forged on the backs of trusting Indians.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(42, "The Arrival of the Mail Train (L'Arrivée d'un train à La Ciotat)", "Another of the Lumiere Brothers' one-shot films, this time showing a steam train arriving at a station and moving towards the camera It has passed into film folklore for the incident that occurred at its world premiere, when the audience, unfamiliar with the cinema thought the train was really coming right at them, and panicked!", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(44, "The Arrival", "An extraterrestrial crash-lands on Earth and decides to take up residence inside the body of an unsuspecting 73-year-old farmer. The occupied farmer seems OK until he starts having a definite craving for human blood, particularly the blood of menstruating women. So he heads out on a cross-country trek supping on sweethearts at a voracious rate. He settles in San Diego where he's fallen in love with a beautiful nurse. (His love of the ladies isn't limited to just their blood.) Soon an FBI agent is on his tail in hot pursuit. This film contains violence, nudity, and profanity.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(45, "Xombie: Dead on Arrival", "A heroic zombie with a conscience and a big shovel fights to reunite a frightened little girl with her desperate parents in this animated romp that proves flesh-eaters are people, too.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(48, "The Day He Arrives", "A film director who no longer makes films, Seongjun, arrives in Seoul to meet a close friend. When the friend doesn't show up, Seongjun wanders the city aimlessly. He runs into an actress he used to know, shares a drink with some film students and against his better judgment, heads to his ex-girlfriend's apartment. The next day goes very much like the last; Seongjun meets the actress, has drinks with friends, and falls for woman who looks remarkably like his ex-girlfriend. Each new day plays out like a flimsy copy of the previous one, but only Seongjun knows why. Infused with a playfulness and dry wit that recalls the films of Woody Allen and Eric Rohmer, The Day He Arrives is a delightful meditation on relationships, filmmaking, and the unknowable forces that govern our lives. -- (C) Official Site", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(49, "The Arrival of Wang (L'arrivo di Wang)", "This intriguing and ambiguous low-budget Italian sci-fi mystery tells the story of a translator who is given a very unusual assignment. Gaia makes her living translating Chinese into Italian. Her latest job offer is a lucrative one, though it quickly becomes apparent that it won't be a run-of-the-mill movie translation this time around, as she's blindfolded and taken to an undisclosed location in the Italian capital. Her curiosity deepens as she's placed in a completely dark room and instructed to act as the intermediary between her employers and whoever else is in the room. As soon as the assignment begins it's apparent that she's now facilitating a harsh interrogation rather than an interview. But whatever she may have thought was going on cannot possibly prepare her for the eventual discovery of who she is actually talking to. And that's just the first of the shocking challenges to her world view... With Ennio Fantastichini as the government agent and Li Yong as the voice of Wang.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(50, "When the Iron Bird Flies: Tibetan Buddhism Arrives in the West", "When the Iron Bird Flies traces the astounding path of one of the world's great spiritual traditions from the caves of Tibet to the mainstream of western culture and asks: In these increasingly chaotic modern times, can these age old teachings help us find genuine happiness and create a saner, more compassionate 21st century world?", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(52, "Arrival", "When mysterious spacecraft touch down across the globe, an elite team--lead by expert linguist Louise Banks (Amy Adams)--are brought together to investigate. As mankind teeters on the verge of global war, Banks and the team race against time for answers--and to find them, she will take a chance that could threaten her life, and quite possibly humanity.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(53, "Before We Arrive: The Story Of The Weber Brothers", "Ryan and Sam Weber are extremely talented, hard-working, storied musicians, who struggle to define success--a confusing and elusive concept for any artist. Their journey to this point has provided them with countless opportunities to learn more about themselves and what really matters in life. Their career has been both rewarding, and punishing. With archival footage dating back to their beginnings, and interviews with the brothers, their band, and a selection of their myriad musical peers, we see why they remain optimistic. The Weber Brothers don't get tied up in the tediousness of striving for fame, fortune, or mainstream success. For the Weber Brothers, it is simply about making music.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(55, "A Dragon Arrives! (Ejdeha Vared Mishavad!)", "A surrealist film set on the island of Qeshm in the Strait of Hormuz, in 1965, in the aftermath of the assassination of Iranian Prime Minister Hassan Ali Mansour. Three individuals? a police inspector, a sound engineer and a geologist? They are in charge of investigating the suspicious death of a political exile. The other conundrum that the trio will have to solve is because, each time someone is buried on the island, an earthquake occurs and someone disappears.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(56, "Three Women Arrive", "A short fashion film.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(57, "UFO Chronicles: The Aliens Arrive", "A former military sergeant's claims that he collected UFO parts and artifacts, along with alien bodies at crash sites, for the U.S. government is investigated.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(58, "Dead On Arrival", "When a sales rep (Billy Flynn) for a pharmaceutical company visits Louisiana on a business trip, he gets roped into a deadly and corrupt world. He is soon poisoned and has only 24 hours to live, and finds himself on the run from both local cops and the mob. D.B. Sweeney and Lillo Brancato co-star. Written and directed by Stephen C. Sepher.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(59, "Captain America: Civil War", "Marvel's "Captain America: Civil War" finds Steve Rogers leading the newly formed team of Avengers in their continued efforts to safeguard humanity. But after another incident involving the Avengers results in collateral damage, political pressure mounts to install a system of accountability, headed by a governing body to oversee and direct the team. The new status quo fractures the Avengers, resulting in two camps-one led by Steve Rogers and his desire for the Avengers to remain free to defend humanity without government interference, and the other following Tony Stark's surprising decision to support government oversight and accountability.", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(60, "Deadpool", "Based upon Marvel Comics' most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life. (C) Fox", 0,0,0,0);

insert into MOVIE(id, title, description, audience_score, blazing_score, box_office, run_time) values(61, "Deadpool 2", "After surviving a near fatal bovine attack, a disfigured cafeteria chef (Wade Wilson) struggles to fulfill his dream of becoming Mayberry's hottest bartender while also learning to cope with his lost sense of taste. Searching to regain his spice for life, as well as a flux capacitor, Wade must battle ninjas, the yakuza, and a pack of sexually aggressive canines, as he journeys around the world to discover the importance of family, friendship, and flavor - finding a new taste for adventure and earning the coveted coffee mug title of World's Best Lover.", 0,0,0,0);

